import streamlit as st


#import streamlit_analytics

#streamlit_analytics.start_tracking()
#streamlit_analytics.stop_tracking()

img = "./images/DGAT_Training.png"


st.markdown("<h2 style='text-align: center;  color: black;'>DGATviz: Interactive Visualization of Spatially Imputed Protein Expression", unsafe_allow_html=True)

st.write("")

st.image(img)

st.write("")
st.write("")

# st.markdown('➡️ Read our paper here: https://www.google.com')   

#desc1 = "Spatial Transcriptomics (ST) technologies have revolutionized our understanding of the tumor microenvironment (TME) by enabling the mapping of gene expression within the spatial context of tissues. However, mRNA levels do not always correlate with protein abundance, which is crucial for understanding cellular functions and interactions. To address this gap, we developed DGAT (Dual-Graph Attention Network), a novel computational framework that integrates gene profiles and spatial information to predict protein expression from ST data."
desc2 = "This is a user-friendly web application for DGAT imputation, allowing researchers to upload their spatial transcriptomics datasets and obtain predicted protein expression profiles. Visualization previews of predicted protein landscapes are also available within the app."
desc3 = "DGATviz is an interactive web platform for exploring spatially imputed protein expression generated by the Dual-Graph Attention Network (DGAT)."
desc4 = "It allows users to upload spatial transcriptomics data, visualize predicted protein landscapes, and perform analyses such as differential expression, co-expression, spatial mapping, and drug-target exploration."
desc5 = "DGATviz bridges transcriptomic and proteomic information to reveal cellular states, immune phenotypes, and spatial organization within tissues."

#st.markdown(f"<p style='text-align: justify; color: black; font-size:18px'>{desc1}</p>", unsafe_allow_html=True)
st.markdown(f"<p style='text-align: justify; color: black; font-size:18px'>{desc3}</p>", unsafe_allow_html=True) 
st.markdown(f"<p style='text-align: justify; color: black; font-size:18px'>{desc4}</p>", unsafe_allow_html=True) 
st.markdown(f"<p style='text-align: justify; color: black; font-size:18px'>{desc5}</p>", unsafe_allow_html=True) 

st.write("")
st.markdown(
    '📚 <span style="color:brown;">Read our preprint here!</span> <br> [DGAT: A Dual-Graph Attention Network for Inferring Spatial Protein Landscapes from Transcriptomics](https://www.biorxiv.org/content/10.1101/2025.07.05.662121v1)',
    unsafe_allow_html=True
)

